apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpcbin-app
  template:
    metadata:
      labels:
        app: grpcbin-app
    spec:
      containers:
      - image: ghcr.io/anddd7/grpcbin:latest
        name: grpcbin
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
