namespace: rubber-duck
commonAnnotations:
  rubber-duck/component: excalidraw
  rubber-duck/managed-by: kustomization
  rubber-duck/overlays: ingress

resources:
- ../../base
- ingress-frontend.yaml
- ingress-room.yaml
- ingress-storage.yaml

patches:
- path: configmap.yaml
