namePrefix: sn-
namespace: rubber-duck
commonAnnotations:
  rubber-duck/scenarios: oauth-github

resources:
- ../../httpbin/kustomization/overlays/ingress
- ingress.yaml
- ../../oauth2-proxy/kustomization/base

patches:
# overwrite the ingress with tls
- path: ingress-httpbin.yaml
# overwrite the credentials
- path: secret.yaml
