repos:
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.18.3
  hooks:
  - id: gitleaks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-added-large-files
  - id: check-json
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  # - id: check-merge-conflict
  # - id: check-xml
  # - id: check-toml
  # - id: file-contents-sorter
