apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: your-app-oauth
spec:
  rules:
  - host: <host>
    http:
      paths:
      - backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
        path: /oauth2
        pathType: Prefix
  tls:
  - hosts:
    - <tls-host>
    secretName: <tls-cert>
