apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: excalidraw-room
  name: excalidraw-room
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excalidraw-room
  template:
    metadata:
      labels:
        app: excalidraw-room
    spec:
      containers:
      - image: docker.io/excalidraw/excalidraw-room:sha-49bf529
        name: room
        env:
        - name: PORT
          value: "8082"
        ports:
        - containerPort: 8082
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8082
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8082
          initialDelaySeconds: 3
          periodSeconds: 10
