commonAnnotations:
  rubber-duck/component: poker-planning
  rubber-duck/managed-by: poker-planning/kustomization/ingress
  rubber-duck/overlays: ingress-demo

resources:
- ../../base
- ingress-frontend.yaml
- ingress-server.yaml

patches:
- path: configmap.yaml
