namespace: rubber-duck
commonAnnotations:
  rubber-duck/component: poker-planning
  rubber-duck/managed-by: kustomization
  rubber-duck/overlays: ingress

resources:
- ../../base
- ingress-frontend.yaml
- ingress-server.yaml

patches:
- path: configmap.yaml
