apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: poker-planning-server
  name: poker-planning-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poker-planning-server
  template:
    metadata:
      labels:
        app: poker-planning-server
    spec:
      containers:
      - image: docker.io/anddd9527/poker-planning-server:v1.0.0
        name: server
        env:
        - name: APP_APPLICATION__BASE_URL
          valueFrom:
            configMapKeyRef:
              name: poker-planning-config
              key: APP_APPLICATION__BASE_URL
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /health_check
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health_check
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 10
