apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: poker-planning-frontend
  name: poker-planning-frontend
spec:
  selector:
    matchLabels:
      app: poker-planning-frontend
  template:
    metadata:
      labels:
        app: poker-planning-frontend
    spec:
      containers:
      - image: docker.io/anddd9527/poker-planning:v1.0.1
        name: frontend
        env:
        - name: GRAPHQL_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: poker-planning-config
              key: GRAPHQL_ENDPOINT
        - name: GRAPHQL_WS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: poker-planning-config
              key: GRAPHQL_WS_ENDPOINT
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10
