apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grpcbin
spec:
  rules:
  - host: grpcbin.example.com
    http:
      paths:
      - backend:
          service:
            name: grpcbin
            port:
              number: 50051
        path: /
        pathType: Prefix
