namespace: rubber-duck
commonAnnotations:
  rubber-duck/component: ls
  rubber-duck/managed-by: kustomization
  rubber-duck/overlays: pvc

resources:
- ../../base
- pvc.yaml

patches:
- path: pod.yaml

