apiVersion: v1
kind: Pod
metadata:
  name: ls-pod
spec:
  containers:
  - name: ls-container
    image: alpine
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: "/mnt"
      name: ls-volume
  volumes:
  - name: ls-volume
    persistentVolumeClaim:
      claimName: ls-pvc
