apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        volumeMounts:
        - name: nginx-configs
          mountPath: /etc/nginx/conf.d
        - name: nginx-htmls
          mountPath: /usr/share/nginx/html
        - name: nginx-ext-htmls
          mountPath: /usr/share/nginx/html/ext
      volumes:
      - name: nginx-configs
        configMap:
          name: nginx-configs
      - name: nginx-htmls
        configMap:
          name: nginx-htmls
      - name: nginx-ext-htmls
        configMap:
          name: nginx-ext-htmls
          items:
          - key: page1.html
            path: page1.html
          - key: subpage1.html
            path: sub/page1.html
